name: Continuous Integration Build

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

env:
  MLE_ROOT: C:\opt\MagicLantern
  
jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add msbuild to Path
        uses: microsoft/setup-msbuild@v2
        with:
            msbuild-architecture: x64
      - uses: milliewalky/setup-7-zip@v2
      - name: Install dependencies
        shell: cmd
        run: |
          mkdir %MLE_ROOT%
          curl -k -LO https://github.com/magic-lantern-studio/mle-ci/releases/download/mlutil-msvc17-latest/mlutil-release.zip
          7z x mlutil-release.zip -o%MLE_ROOT%
          dir %MLE_ROOT%\MagicLantern
      - name: Build with msbuild
        shell: cmd
        run: |
          cd math\win32\build\msvc17
          msbuild mlmath.sln /p:Configuration=Release /p:Platform=x64
