name: Continuous Integration Build

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create build directory and run CMake
        shell: cmd
        run: |
          pwd
