name: Continuous Integration Build

on:
  workflow_dispatch:  # Allow manual triggers
  push:
    branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Add msbuild to Path
        uses: microsoft/setup-msbuild@v1
        with:
            msbuild-architecture: x64
      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
        with:
            sdk-version: 15063
      - name: Build with msbuild
        shell: cmd
        run: |
          cd math\win32\build\msvc15 
          pwd
          dir
          msbuild mlmath.sln
